In [12]:
import pandas as pd

df = pd.read_excel("AG_PRD_FIESMS.xlsx")

In [13]:
df.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Age,Freq,Location,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,47.7,52.8,57.8,62.8,69.9,78.2,85.5,85.5,84.5,NaN
1,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,42.6,46.5,50.8,52.4,56.5,62.0,72.8,76.4,77.0,NaN
2,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,ALLAGE,NaN,ALLAREA,...,45.1,49.6,54.3,57.6,63.1,70.1,79.1,80.9,80.8,NaN

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1084 entries, 0 to 1083
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Goal                1084 non-null   int64
 1   Target              1084 non-null   float64
 2   Indicator           1084 non-null   str
 3   SeriesCode          1084 non-null   str
 4   SeriesDescription   1084 non-null   str
 5   GeoAreaCode         1084 non-null   int64
 6   GeoAreaName         1084 non-null   str
 7   Age                 1084 non-null   str
 8   Freq                0 non-null      float64
 9   Location            1084 non-null   str
 10  Observation Status  1084 non-null   str
 11  Reporting Type      1084 non-null   str
 12  Sex                 1084 non-null   str
 13  Units               1084 non-null   str
 14  2015                297 non-null    float64
 15  2016                300 non-null    float64
 16  2017                345 non-null    float64
 17  2018                364 non-null    float64
 18  2019                406 non-null    float64
 19  2020                430 non-null    float64
 20  2021                438 non-null    float64
 21  2022                435 non-null    float64
 22  2023                402 non-null    float64
 23  2024                0 non-null      float64
dtypes: float64(12), int64(2), str(10)
memory usage: 203.4 KB

In [16]:
df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription","Observation Status", "Reporting Type"], inplace=True)

In [17]:
df.head()

,GeoAreaCode,GeoAreaName,Age,Freq,Location,Sex,Units,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,15+,NaN,ALLAREA,FEMALE,PERCENT,47.7,52.8,57.8,62.8,69.9,78.2,85.5,85.5,84.5,NaN
1,4,Afghanistan,15+,NaN,ALLAREA,MALE,PERCENT,42.6,46.5,50.8,52.4,56.5,62.0,72.8,76.4,77.0,NaN
2,4,Afghanistan,15+,NaN,ALLAREA,FEMALE,PERCENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Afghanistan,15+,NaN,ALLAREA,MALE,PERCENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Afghanistan,ALLAGE,NaN,ALLAREA,BOTHSEX,PERCENT,45.1,49.6,54.3,57.6,63.1,70.1,79.1,80.9,80.8,NaN

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1084 entries, 0 to 1083
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  1084 non-null   int64
 1   GeoAreaName  1084 non-null   str
 2   Age          1084 non-null   str
 3   Freq         0 non-null      float64
 4   Location     1084 non-null   str
 5   Sex          1084 non-null   str
 6   Units        1084 non-null   str
 7   2015         297 non-null    float64
 8   2016         300 non-null    float64
 9   2017         345 non-null    float64
 10  2018         364 non-null    float64
 11  2019         406 non-null    float64
 12  2020         430 non-null    float64
 13  2021         438 non-null    float64
 14  2022         435 non-null    float64
 15  2023         402 non-null    float64
 16  2024         0 non-null      float64
dtypes: float64(11), int64(1), str(5)
memory usage: 144.1 KB

In [19]:
# transforming wide to long table
year_cols = [str(y) for y in range(2015, 2025)]

df_long = df.melt(
    id_vars=["GeoAreaCode", "GeoAreaName", "Age", "Location", "Sex", "Units"],
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

df_long.head()

   GeoAreaCode  GeoAreaName     Age Location      Sex    Units  Year  Value
0            4  Afghanistan     15+  ALLAREA   FEMALE  PERCENT  2015   47.7
1            4  Afghanistan     15+  ALLAREA     MALE  PERCENT  2015   42.6
2            4  Afghanistan     15+  ALLAREA   FEMALE  PERCENT  2015    NaN
3            4  Afghanistan     15+  ALLAREA     MALE  PERCENT  2015    NaN
4            4  Afghanistan  ALLAGE  ALLAREA  BOTHSEX  PERCENT  2015   45.1

In [20]:
df_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  10840 non-null  int64
 1   GeoAreaName  10840 non-null  str
 2   Age          10840 non-null  str
 3   Location     10840 non-null  str
 4   Sex          10840 non-null  str
 5   Units        10840 non-null  str
 6   Year         10840 non-null  str
 7   Value        3417 non-null   float64
dtypes: float64(1), int64(1), str(6)
memory usage: 677.6 KB

In [21]:
df_long.to_csv("food_insecurity.csv", index=False)

## Workflow

```python
def clean_melt_df(xlFile):
    df = pd.read_excel(xlFile)
    df.info()
    df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription","Observation Status", "Reporting Type"], inplace=True)
    df.info()
    # transforming wide to long table
    year_cols = [str(y) for y in range(2015, 2025)]
    fixed_columns = ["GeoAreaCode", "GeoAreaName", "Age", "Location", "Sex", "Units"]

    df_long = df.melt(
        id_vars=fixed_columns,
        value_vars=year_cols,
        var_name="Year",
        value_name="Value"
    )

    df_long.head()
    return df_long
```

In [ ]:
df = pd.read_excel("SI_POV_NAHC.xlsx")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Goal               157 non-null    int64
 1   Target             157 non-null    float64
 2   Indicator          157 non-null    str
 3   SeriesCode         157 non-null    str
 4   SeriesDescription  157 non-null    str
 5   GeoAreaCode        157 non-null    int64
 6   GeoAreaName        157 non-null    str
 7   Age                0 non-null      float64
 8   Location           157 non-null    str
 9   Reporting Type     157 non-null    str
 10  Sex                0 non-null      float64
 11  Units              157 non-null    str
 12  2000               14 non-null     float64
 13  2001               16 non-null     float64
 14  2002               18 non-null     float64
 15  2003               19 non-null     float64
 16  2004               30 non-null     float64
 17  2005               43 non-null     float64
 18  2006               41 non-null     float64
 19  2007               45 non-null     float64
 20  2008               39 non-null     float64
 21  2009               50 non-null     float64
 22  2010               51 non-null     float64
 23  2011               53 non-null     float64
 24  2012               52 non-null     float64
 25  2013               48 non-null     float64
 26  2014               49 non-null     float64
 27  2015               59 non-null     float64
 28  2016               58 non-null     float64
 29  2017               54 non-null     float64
 30  2018               66 non-null     float64
 31  2019               64 non-null     float64
 32  2020               57 non-null     float64
 33  2021               64 non-null     float64
 34  2022               40 non-null     float64
 35  2023               15 non-null     float64
 36  2024               1 non-null      float64
dtypes: float64(28), int64(2), str(7)
memory usage: 45.5 KB

In [ ]:
df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription", "Reporting Type"], inplace=True)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  157 non-null    int64
 1   GeoAreaName  157 non-null    str
 2   Age          0 non-null      float64
 3   Location     157 non-null    str
 4   Sex          0 non-null      float64
 5   Units        157 non-null    str
 6   2000         14 non-null     float64
 7   2001         16 non-null     float64
 8   2002         18 non-null     float64
 9   2003         19 non-null     float64
 10  2004         30 non-null     float64
 11  2005         43 non-null     float64
 12  2006         41 non-null     float64
 13  2007         45 non-null     float64
 14  2008         39 non-null     float64
 15  2009         50 non-null     float64
 16  2010         51 non-null     float64
 17  2011         53 non-null     float64
 18  2012         52 non-null     float64
 19  2013         48 non-null     float64
 20  2014         49 non-null     float64
 21  2015         59 non-null     float64
 22  2016         58 non-null     float64
 23  2017         54 non-null     float64
 24  2018         66 non-null     float64
 25  2019         64 non-null     float64
 26  2020         57 non-null     float64
 27  2021         64 non-null     float64
 28  2022         40 non-null     float64
 29  2023         15 non-null     float64
 30  2024         1 non-null      float64
dtypes: float64(27), int64(1), str(3)
memory usage: 38.2 KB

In [ ]:
year_cols = [str(y) for y in range(2000, 2025)]
fixed_columns = ["GeoAreaCode", "GeoAreaName", "Age", "Location", "Sex", "Units"]

df_long = df.melt(
    id_vars=fixed_columns,
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

df_long.head()

   GeoAreaCode  GeoAreaName  Age Location  Sex    Units  Year  Value
0            4  Afghanistan  NaN  ALLAREA  NaN  PERCENT  2000    NaN
1            8      Albania  NaN  ALLAREA  NaN  PERCENT  2000    NaN
2           12      Algeria  NaN  ALLAREA  NaN  PERCENT  2000    NaN
3           24       Angola  NaN  ALLAREA  NaN  PERCENT  2000    NaN
4           32    Argentina  NaN    URBAN  NaN  PERCENT  2000    NaN

In [ ]:
df_long.to_csv("below_poverty_line.csv", index=False)

In [ ]:
df = pd.read_excel("SH_STA_SCIDE.xlsx")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Goal               555 non-null    int64
 1   Target             555 non-null    float64
 2   Indicator          555 non-null    str
 3   SeriesCode         555 non-null    str
 4   SeriesDescription  555 non-null    str
 5   GeoAreaCode        555 non-null    int64
 6   GeoAreaName        555 non-null    str
 7   Reporting Type     555 non-null    str
 8   Sex                555 non-null    str
 9   Units              555 non-null    str
 10  2000               555 non-null    float64
 11  2005               555 non-null    float64
 12  2010               555 non-null    float64
 13  2015               555 non-null    float64
 14  2019               555 non-null    float64
 15  2020               555 non-null    float64
 16  2021               555 non-null    float64
dtypes: float64(8), int64(2), str(7)
memory usage: 73.8 KB

In [ ]:
df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription", "Reporting Type"], inplace=True)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  555 non-null    int64
 1   GeoAreaName  555 non-null    str
 2   Sex          555 non-null    str
 3   Units        555 non-null    str
 4   2000         555 non-null    float64
 5   2005         555 non-null    float64
 6   2010         555 non-null    float64
 7   2015         555 non-null    float64
 8   2019         555 non-null    float64
 9   2020         555 non-null    float64
 10  2021         555 non-null    float64
dtypes: float64(7), int64(1), str(3)
memory usage: 47.8 KB

In [ ]:
year_cols = ['2000', '2005', '2010', '2015', '2019','2020', '2021']
fixed_columns = ["GeoAreaCode", "GeoAreaName", "Sex", "Units"]

df_long = df.melt(
    id_vars=fixed_columns,
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

df_long.head()

   GeoAreaCode  GeoAreaName      Sex           Units  Year  Value
0            4  Afghanistan  BOTHSEX  PER_100000_POP  2000    4.4
1            4  Afghanistan   FEMALE  PER_100000_POP  2000    2.9
2            4  Afghanistan     MALE  PER_100000_POP  2000    5.8
3            8      Albania  BOTHSEX  PER_100000_POP  2000    4.8
4            8      Albania   FEMALE  PER_100000_POP  2000    3.3

In [ ]:
df_long.to_csv("suicide_rate.csv", index=False)

In [ ]:
df = pd.read_excel("SH_ALC_CONSPT.xlsx")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Goal                189 non-null    int64
 1   Target              189 non-null    float64
 2   Indicator           189 non-null    str
 3   SeriesCode          189 non-null    str
 4   SeriesDescription   189 non-null    str
 5   GeoAreaCode         189 non-null    int64
 6   GeoAreaName         189 non-null    str
 7   Age                 189 non-null    str
 8   Observation Status  0 non-null      float64
 9   Reporting Type      189 non-null    str
 10  Sex                 189 non-null    str
 11  Units               189 non-null    str
 12  2000                188 non-null    float64
 13  2001                188 non-null    float64
 14  2002                188 non-null    float64
 15  2003                188 non-null    float64
 16  2004                188 non-null    float64
 17  2005                188 non-null    float64
 18  2006                188 non-null    float64
 19  2007                188 non-null    float64
 20  2008                188 non-null    float64
 21  2009                188 non-null    float64
 22  2010                188 non-null    float64
 23  2011                188 non-null    float64
 24  2012                188 non-null    float64
 25  2013                188 non-null    float64
 26  2014                188 non-null    float64
 27  2015                188 non-null    float64
 28  2016                188 non-null    float64
 29  2017                188 non-null    float64
 30  2018                188 non-null    float64
 31  2019                188 non-null    float64
 32  2020                188 non-null    float64
 33  2021                188 non-null    float64
 34  2022                188 non-null    float64
dtypes: float64(25), int64(2), str(8)
memory usage: 51.8 KB

In [ ]:
df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription", "Observation Status", "Reporting Type"], inplace=True)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  189 non-null    int64
 1   GeoAreaName  189 non-null    str
 2   Age          189 non-null    str
 3   Sex          189 non-null    str
 4   Units        189 non-null    str
 5   2000         188 non-null    float64
 6   2001         188 non-null    float64
 7   2002         188 non-null    float64
 8   2003         188 non-null    float64
 9   2004         188 non-null    float64
 10  2005         188 non-null    float64
 11  2006         188 non-null    float64
 12  2007         188 non-null    float64
 13  2008         188 non-null    float64
 14  2009         188 non-null    float64
 15  2010         188 non-null    float64
 16  2011         188 non-null    float64
 17  2012         188 non-null    float64
 18  2013         188 non-null    float64
 19  2014         188 non-null    float64
 20  2015         188 non-null    float64
 21  2016         188 non-null    float64
 22  2017         188 non-null    float64
 23  2018         188 non-null    float64
 24  2019         188 non-null    float64
 25  2020         188 non-null    float64
 26  2021         188 non-null    float64
 27  2022         188 non-null    float64
dtypes: float64(23), int64(1), str(4)
memory usage: 41.5 KB

In [ ]:
year_cols = [str(y) for y in range(2000, 2023)]
print(year_cols)
fixed_columns = ["GeoAreaCode", "GeoAreaName", "Sex", "Age","Units"]

df_long = df.melt(
    id_vars=fixed_columns,
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

df_long.head()

['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

   GeoAreaCode  GeoAreaName      Sex  Age     Units  Year     Value
0            4  Afghanistan  BOTHSEX  15+  LTPUREAL  2000   0.00466
1            8      Albania  BOTHSEX  15+  LTPUREAL  2000   5.09167
2           12      Algeria  BOTHSEX  15+  LTPUREAL  2000   0.38691
3           20      Andorra  BOTHSEX  15+  LTPUREAL  2000  13.34070
4           24       Angola  BOTHSEX  15+  LTPUREAL  2000   5.75013

In [ ]:
df_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 4347 entries, 0 to 4346
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  4347 non-null   int64
 1   GeoAreaName  4347 non-null   str
 2   Sex          4347 non-null   str
 3   Age          4347 non-null   str
 4   Units        4347 non-null   str
 5   Year         4347 non-null   str
 6   Value        4324 non-null   float64
dtypes: float64(1), int64(1), str(5)
memory usage: 237.9 KB

In [ ]:
df_long.to_csv("alcohol_consumption.csv", index=False)