In [12]:
import pandas as pd

df = pd.read_excel("AG_PRD_FIESMS.xlsx")

In [13]:
df.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Age,Freq,Location,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,47.7,52.8,57.8,62.8,69.9,78.2,85.5,85.5,84.5,NaN
1,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,42.6,46.5,50.8,52.4,56.5,62.0,72.8,76.4,77.0,NaN
2,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,15+,NaN,ALLAREA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,2.1,2.1.2,AG_PRD_FIESMS,Prevalence of moderate or severe food insecuri...,4,Afghanistan,ALLAGE,NaN,ALLAREA,...,45.1,49.6,54.3,57.6,63.1,70.1,79.1,80.9,80.8,NaN

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1084 entries, 0 to 1083
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Goal                1084 non-null   int64
 1   Target              1084 non-null   float64
 2   Indicator           1084 non-null   str
 3   SeriesCode          1084 non-null   str
 4   SeriesDescription   1084 non-null   str
 5   GeoAreaCode         1084 non-null   int64
 6   GeoAreaName         1084 non-null   str
 7   Age                 1084 non-null   str
 8   Freq                0 non-null      float64
 9   Location            1084 non-null   str
 10  Observation Status  1084 non-null   str
 11  Reporting Type      1084 non-null   str
 12  Sex                 1084 non-null   str
 13  Units               1084 non-null   str
 14  2015                297 non-null    float64
 15  2016                300 non-null    float64
 16  2017                345 non-null    float64
 17  2018                364 non-null    float64
 18  2019                406 non-null    float64
 19  2020                430 non-null    float64
 20  2021                438 non-null    float64
 21  2022                435 non-null    float64
 22  2023                402 non-null    float64
 23  2024                0 non-null      float64
dtypes: float64(12), int64(2), str(10)
memory usage: 203.4 KB

In [16]:
df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription","Observation Status", "Reporting Type"], inplace=True)

In [17]:
df.head()

,GeoAreaCode,GeoAreaName,Age,Freq,Location,Sex,Units,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,4,Afghanistan,15+,NaN,ALLAREA,FEMALE,PERCENT,47.7,52.8,57.8,62.8,69.9,78.2,85.5,85.5,84.5,NaN
1,4,Afghanistan,15+,NaN,ALLAREA,MALE,PERCENT,42.6,46.5,50.8,52.4,56.5,62.0,72.8,76.4,77.0,NaN
2,4,Afghanistan,15+,NaN,ALLAREA,FEMALE,PERCENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Afghanistan,15+,NaN,ALLAREA,MALE,PERCENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Afghanistan,ALLAGE,NaN,ALLAREA,BOTHSEX,PERCENT,45.1,49.6,54.3,57.6,63.1,70.1,79.1,80.9,80.8,NaN

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1084 entries, 0 to 1083
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  1084 non-null   int64
 1   GeoAreaName  1084 non-null   str
 2   Age          1084 non-null   str
 3   Freq         0 non-null      float64
 4   Location     1084 non-null   str
 5   Sex          1084 non-null   str
 6   Units        1084 non-null   str
 7   2015         297 non-null    float64
 8   2016         300 non-null    float64
 9   2017         345 non-null    float64
 10  2018         364 non-null    float64
 11  2019         406 non-null    float64
 12  2020         430 non-null    float64
 13  2021         438 non-null    float64
 14  2022         435 non-null    float64
 15  2023         402 non-null    float64
 16  2024         0 non-null      float64
dtypes: float64(11), int64(1), str(5)
memory usage: 144.1 KB

In [19]:
# transforming wide to long table
year_cols = [str(y) for y in range(2015, 2025)]

df_long = df.melt(
    id_vars=["GeoAreaCode", "GeoAreaName", "Age", "Location", "Sex", "Units"],
    value_vars=year_cols,
    var_name="Year",
    value_name="Value"
)

df_long.head()

   GeoAreaCode  GeoAreaName     Age Location      Sex    Units  Year  Value
0            4  Afghanistan     15+  ALLAREA   FEMALE  PERCENT  2015   47.7
1            4  Afghanistan     15+  ALLAREA     MALE  PERCENT  2015   42.6
2            4  Afghanistan     15+  ALLAREA   FEMALE  PERCENT  2015    NaN
3            4  Afghanistan     15+  ALLAREA     MALE  PERCENT  2015    NaN
4            4  Afghanistan  ALLAGE  ALLAREA  BOTHSEX  PERCENT  2015   45.1

In [20]:
df_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoAreaCode  10840 non-null  int64
 1   GeoAreaName  10840 non-null  str
 2   Age          10840 non-null  str
 3   Location     10840 non-null  str
 4   Sex          10840 non-null  str
 5   Units        10840 non-null  str
 6   Year         10840 non-null  str
 7   Value        3417 non-null   float64
dtypes: float64(1), int64(1), str(6)
memory usage: 677.6 KB

In [21]:
df_long.to_csv("food_insecurity.csv", index=False)

## Workflow

```python
def clean_melt_df(xlFile):
    df = pd.read_excel(xlFile)
    df.info()
    df.drop(columns=["Goal", "Target", "Indicator", "SeriesCode", "SeriesDescription","Observation Status", "Reporting Type"], inplace=True)
    df.info()
    # transforming wide to long table
    year_cols = [str(y) for y in range(2015, 2025)]
    fixed_columns = ["GeoAreaCode", "GeoAreaName", "Age", "Location", "Sex", "Units"]

    df_long = df.melt(
        id_vars=fixed_columns,
        value_vars=year_cols,
        var_name="Year",
        value_name="Value"
    )

    df_long.head()
    return df_long
```